import Head from 'next/head'
import Image from 'next/image'
import styles from './styles/i.module.css'
import { getSortedPostsData } from '../lib/posts';
import { Direc } from '../components/Directory';

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return { 
    props: {
      allPostsData,
    },
  };
}

export default function Home({ allPostsData }) {
  return (
    <main>
    <div className={styles.container}>
      <Head>
        <title>BMBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.Header_0}>
          <div className={styles.Header_left}>
            <a href="#">
              <span className={styles.Logo}>Better</span>
              <span className={styles.Logo}>~</span>
              <span className={styles.Logo}>Multiply</span>
            </a>
          </div>
          <div className={styles.Header_right}>
            <span><a className={styles.sp} href='#'>Latest</a></span>
            <span><a className={styles.sp} href='#'>Recommend</a></span>
            <span><a className={styles.sp} href='#'>Notes</a></span>
            <span><a className={styles.sp} href='#'>About_BM</a></span>
          </div>
        </header>
        <h1 className={styles.title}>
          <div>Welcome</div>
          <div><a href="https://nextjs.org">{"It's BM' s Blog!"}</a></div>
        </h1>
        
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
            <Image src="/profile.jpg" alt="lovelive master" width={244} height={244} />
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      <Direc allPostsData={allPostsData}></Direc>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    <section>
        <h2>Blog</h2>
        <ul>
          {allPostsData.map(({ id, date, title }) => (
            <li key={id}>
              {title}
              <br />
              {id}
              <br />
              {date}
            </li>
          ))}
        </ul>
      </section>
      
      </main>
  )
}
